### ISSUE TITLE
Question about background image

### ISSUE THREAD

**Issue by yellowjs0304** [clovaai/synthtiger#12]
Hi, @moonbings Thank you for sharing nice work.

I wonder where's the code that load background image such as below?

![image](https://user-images.githubusercontent.com/30281608/149881268-44962c70-376a-46d3-9c33-376193c3a99f.png)

And I also wonder when the Synthdog will be released

**Comment by moonbings** [comment]
Hi, thank you for your interest.

---

**First question**

This example seems to be modified from [this image](https://github.com/clovaai/synthtiger/blob/master/resources/image/bob%2Bdylan_83.jpg) (image cropping and color change).
Code for loading and cropping images is [here](https://github.com/clovaai/synthtiger/blob/master/synthtiger/components/texture/base_texture.py). If `crop` probability value is greater than `0`, images are randomly cropped.
And code for changing color of images is [here](https://github.com/clovaai/synthtiger/blob/master/synthtiger/components/color/rgb.py) (or [here](https://github.com/clovaai/synthtiger/blob/master/synthtiger/components/color/gray.py)). This code randomly selects a color and applies it to layer.

Here's an example code.

```python
from synthtiger import components, layers

texture = components.BaseTexture(..., crop=1)
color = components.RGB()

image = texture.data(texture.sample())
layer = layers.Layer(image)
color.apply([layer])

output = layer.output()
```

**Second question**

The release is under progress. I will tell you when the release date is decided.

---

Thanks.

**Comment by yellowjs0304** [comment]
Thank you for fast reply.

**Comment by moonbings** [comment]
@yellowjs0304 
SynthDog was released today :)
You can use SynthDog and Donut here.
https://github.com/clovaai/donut

If you any questions about SynthDog or Donut, please open issue at donut repo.
Thanks.
