### ISSUE TITLE
Other latin language

### ISSUE THREAD

**Issue by Globolik** [clovaai/synthtiger#20]
Hi, great work !
What exactly should one modify to change language.
I found this:
https://github.com/clovaai/synthtiger/tree/master/resources/charset 
but not sure if I need to generate something from that.

thanks in advance :)

**Comment by moonbings** [comment]
Sorry for the late reply.

---

**You only need corpus and fonts of other language.**
See https://github.com/clovaai/synthtiger#non-latin-language-data-generation for more details.

1. Add corpus to `resources/corpus` path.
2. Add fonts to `resources/font` path.
3. Run script `python tools/extract_font_charset.py -w 4 resources/fonts` to extract renderable charsets for all font files.
4. Run synthtiger.
   `synthtiger -o results -w 4 -v examples/synthtiger/template.py SynthTiger examples/synthtiger/config_horizontal.yaml`

---

And this files (https://github.com/clovaai/synthtiger/tree/master/resources/charset) are used to **control character distribution** (**See 3.2 and 4.5 section in this paper**). This files contain characters that you want to control distribution.
If you want to use character distribution augmentation, see below.

1. Prepare character list file.
   (e.g. https://github.com/clovaai/synthtiger/blob/master/resources/charset/alphanum_special.txt)
2. Change config.
   - https://github.com/clovaai/synthtiger/blob/master/examples/synthtiger/config_horizontal.yaml#L21-L28
     - Fill `paths`  and `weights` values.
     - Change `augmentation` value. This value means character distribution augmentation ratio.
     - Change `augmentation_charset` value. This value must be path to character list file.
       (e.g. `resources/charset/alphanum_special.txt`)
   - https://github.com/clovaai/synthtiger/blob/master/examples/synthtiger/config_horizontal.yaml#L11
     - Change corpus selection weight.
       (e.g. `[1, 0]` -> `[1, 1]`)
3. Run synthtiger.
   `synthtiger -o results -w 4 -v examples/synthtiger/template.py SynthTiger examples/synthtiger/config_horizontal.yaml`

---

Thank you for your interest.
