### ISSUE TITLE
gen.py throws munmap_chunk(): invalid pointer and stops generating images

### ISSUE THREAD

**Issue by arundprabhu** [clovaai/synthtiger#5]
On running gen.py with the command posted in the readme, the process throws 

munmap_chunk(): invalid pointer 

and is stuck. It stops generating images. Each worker generates a maximum of 1 image before this error is thrown.

**Comment by moonbings** [comment]
Hi,
I think this error is related to [this Pillow issue](https://github.com/python-pillow/Pillow/issues/4225).
Is your Pillow version less than 8.2.0?
Could you upgrade Pillow to 8.2.0 or higher?

```
pip install --upgrade "Pillow>=8.2.0"
```

If this problem is solved, I'll update "requirements.txt".
Thanks.
