### ISSUE TITLE
attribute error for numpy

### ISSUE THREAD

**Issue by PriyankaTds** [clovaai/synthtiger#71]
while running synthtiger -o results -w 4 -v examples/synthtiger/template.py SynthTiger examples/synthtiger/config_vertical.yaml:
facing this issue
AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.. Did you mean: 'dtypes'?

**Comment by wvw321** [comment]
Try installing numpy version 1.26.4

**Comment by PriyankaTds** [comment]
Thankyou!
